---
# suricata_ids/tasks/main.yml
# Suricata IDS/IPS installation and configuration

- name: "Suricata | Update package cache"
  ansible.builtin.package:
    update_cache: true
  tags:
    - suricata
    - packages

- name: "Suricata | Install Suricata and dependencies"
  ansible.builtin.package:
    name:
      - suricata
      - suricata-update
      - python3-yaml
      - python3-requests
      - ethtool
    state: present
  tags:
    - suricata
    - packages

- name: "Suricata | Create Suricata directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: suricata
    group: suricata
    mode: '0750'
  loop:
    - /var/log/suricata
    - /var/lib/suricata/rules
    - /var/lib/suricata/update
    - /etc/suricata/rules
  tags:
    - suricata
    - directories

- name: "Suricata | Template Suricata configuration"
  ansible.builtin.template:
    src: suricata.yaml.j2
    dest: /etc/suricata/suricata.yaml
    owner: root
    group: suricata
    mode: '0640'
    backup: true
  notify: restart suricata
  tags:
    - suricata
    - config

- name: "Suricata | Configure Suricata-update"
  ansible.builtin.template:
    src: update.yaml.j2
    dest: /etc/suricata/update.yaml
    owner: root
    group: suricata
    mode: '0640'
  tags:
    - suricata
    - update_config

- name: "Suricata | Update Suricata rulesets"
  ansible.builtin.command:
    cmd: suricata-update --config /etc/suricata/update.yaml
    creates: /var/lib/suricata/rules/suricata.rules
  environment:
    OINKCODE: "{{ suricata_oinkcode | default('') }}"
  notify: restart suricata
  tags:
    - suricata
    - rules_update

- name: "Suricata | Configure network interfaces for IDS mode"
  ansible.builtin.template:
    src: suricata-interfaces.j2
    dest: /etc/systemd/system/suricata.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  when: suricata_mode == 'ids'
  notify:
    - reload systemd
    - restart suricata
  tags:
    - suricata
    - interfaces

- name: "Suricata | Configure for IPS mode (inline)"
  ansible.builtin.template:
    src: suricata-ips.j2
    dest: /etc/systemd/system/suricata.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  when: suricata_mode == 'ips'
  notify:
    - reload systemd
    - restart suricata
  tags:
    - suricata
    - ips_mode

- name: "Suricata | Configure log rotation"
  ansible.builtin.template:
    src: suricata-logrotate.j2
    dest: /etc/logrotate.d/suricata
    owner: root
    group: root
    mode: '0644'
  tags:
    - suricata
    - logging

- name: "Suricata | Create custom rules directory"
  ansible.builtin.file:
    path: /etc/suricata/rules/custom
    state: directory
    owner: root
    group: suricata
    mode: '0750'
  tags:
    - suricata
    - custom_rules

- name: "Suricata | Install custom rules"
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "/etc/suricata/rules/custom/{{ item.name }}"
    owner: root
    group: suricata
    mode: '0640'
  loop: "{{ suricata_custom_rules | default([]) }}"
  notify: restart suricata
  tags:
    - suricata
    - custom_rules

- name: "Suricata | Configure Filebeat for log shipping"
  ansible.builtin.template:
    src: filebeat-suricata.yml.j2
    dest: /etc/filebeat/conf.d/suricata.yml
    owner: root
    group: root
    mode: '0600'
  when: suricata_filebeat_enabled | default(false)
  notify: restart filebeat
  tags:
    - suricata
    - logging
    - filebeat

- name: "Suricata | Enable and start Suricata service"
  ansible.builtin.systemd:
    name: suricata
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - suricata
    - service

- name: "Suricata | Configure performance tuning"
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ suricata_sysctl_settings | default([]) }}"
  tags:
    - suricata
    - performance

- name: "Suricata | Setup rule update cron job"
  ansible.builtin.cron:
    name: "Suricata rule update"
    minute: "{{ suricata_update_minute | default('0') }}"
    hour: "{{ suricata_update_hour | default('2') }}"
    job: "/usr/bin/suricata-update --config /etc/suricata/update.yaml && /bin/systemctl reload suricata"
    user: root
  when: suricata_auto_update | default(true)
  tags:
    - suricata
    - cron

- name: "Suricata | Verify Suricata is running"
  ansible.builtin.systemd:
    name: suricata
    state: started
  register: suricata_status
  tags:
    - suricata
    - verification

- name: "Suricata | Check Suricata logs for errors"
  ansible.builtin.command:
    cmd: journalctl -u suricata --no-pager -n 20
  register: suricata_logs
  changed_when: false
  failed_when: "'FATAL' in suricata_logs.stdout"
  tags:
    - suricata
    - verification
